name: setbit
description: SetBit Feature Flag SDK for Flutter. Simple, fast feature flags for mobile and web apps.
version: 0.1.0
homepage: https://setbit.io
repository: https://github.com/setbit-io/setbit-flutter
documentation: https://docs.setbit.io/sdks/flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
